<div class="row">
	<div class="col-md-12">
		<h1>Contacto</h1>
	</div>
	<div class="col-md-12">
			<h5>Teléfonos y contactos</h5><br>
			<br> <h4> DIRECCION </h4>
			<p>Rio Moctezuma No.5 
			<br>Colinas del Lago, Cuautitlan Izcalli</p>
			<br> <h3> CORREO ELECTRONICO </h3>
			<p><a class="links" href="mailto:sicoplas2005@gmail.com">sicoplas2005@gmail.com</a></p>
			<br> <h4> GABRIEL DELGADO ROSAS </h4>
			<label> Gerente Comercial</label>
			<p>55 3480 - 4751
			<br>55 5817 - 4151
			<br>
			<br><h4> ALFONSO VARGAS</h4>
			<label> Asesor Especilizado </label>
			<br>55 4586 - 0466</p>
		</div>
</div>

<style type="text/css">
	.links{
		color: #000;
	font-family: 'Montserrat Alternates', sans-serif;
	font-size: 15px;
	}

</style>