<div class="row">
	<center>
		<p><h1 class="text-center">Servicio Integral en Control de Plagas</h1></p>
		<p><h1 class="text-center"> y Seguridad Industrial</h1></p>
	</center>
</div><br>
<div class="row" style="border: 1px solid #000000;">
	<div class="col-md-8" style="border: 1px solid #000000;">
		<div class="col-md-12" style="border: 1px solid #000000;">
			<h5>Consulta por Tema</h5><br>
			<p><a href="" class="links">PROCEDIEMIENTO MIP UNIDADES DE TRANSPORTE 2018</a></p>
			<p><a href="" class="links">PROCEDIMEINTO MIP DE CEDIS 2018</a></p>
			<p><a href="" class="links">MEDIO HAMBIENTE</a></p>
			<p><a href="" class="links">SEGURIDAD</a></p>
			<p><a href="" class="links">VIVIENDA</a></p>
		</div>
		<div class="col-md-12" style="border: 1px solid #000000;">
			<h5>Teléfonos y contactos</h5><br>
			<p>Rio Moctezuma No.5 
			<br>Colinas del Lago, Cuautitlan Izcalli</p>
			<p><a href="mailto:sicoplas2005@gmail.com">sicoplas2005@gmail.com</a></p>
			<p>55 3480 - 4751
			<br>55 5817 - 4151
			<br>55 4586 - 0466</p>
		</div>
	</div>
	<div class="col-md-4" style="border: 1px solid #000000;">
		<center>
			<h5>Catálogo de servicios</h5><br>
			<p><a href=""><img src="/img/img_icos/s1.png" width="80" height="80"><br>Articulos</a></p>
			<p><a href=""><img src="/img/img_icos/s2.png" width="80" height="80"><br>Fumigacion</a></p>
			<p><a href=""><img src="/img/img_icos/s3.png" width="80" height="80"><br>Desasolve</a></p>
		</center>
	</div>
</div>