<div class="row">
	<center>
		<p><h1 class="text-center">Servicio Integral en Control de Plagas</h1></p>
		<p><h1 class="text-center"> y Seguridad Industrial</h1></p>
	</center>
</div><br>
<div class="row">
	<div class="col-md-8">
		<div class="col-md-12">
			<h5>Consulta por Tema</h5><br>
			<p><a href="/docs/PUT2018.pdf" class="links">PROCEDIEMIENTO MIP UNIDADES DE TRANSPORTE 2018</a></p>
			<p><a href="/docs/PC2018.pdf" class="links">PROCEDIMEINTO MIP DE CEDIS 2018</a></p>
			<p><a href="" class="links">MEDIO AMBIENTE</a></p>
			<p><a href="" class="links">SEGURIDAD</a></p>
			<p><a href="" class="links">VIVIENDA</a></p>
		</div>
		
	</div>
	<div class="col-md-4">
		<center>
			<h5>Catálogo de servicios</h5><br>
			<p><a href=""><img src="/img/img_icos/s1.png" width="80" height="80"><br>Articulos</a></p>
			<p><a href=""><img src="/img/img_icos/s2.png" width="80" height="80"><br>Fumigacion</a></p>
			<p><a href=""><img src="/img/img_icos/s3.png" width="80" height="80"><br>Desasolve</a></p>
		</center>
	</div>
</div>