<center>
<div class="row" >
  
  <div class="mx-auto d-block">
   <div class="card">
    <div class="card-body">
      <div class="col-lg-12 col-md-12 text-center">
        <br><h2>Iniciar sesion</h2> <br>       
      </div>
      <div class="col-lg-12 col-md-12">
        <form method="POST" action="/index/validar">
          <div class="row">
            <div class="col-lg-12 col-md-12">
              <div class="form-group">
                <label><i class="fa fa-user" aria-hidden="true"></i> Correo</label>
                <input type="text" name="mail"  class="form-control"/>    
              </div>
              <div class="form-group">
                <label><i class="fa fa-lock" aria-hidden="true"></i> Contraseña</label>
                <input type="password" name="passw" class="form-control"/> <br>
              </div>
              <div class="form-group text-center">
                <input type="submit" value="Iniciar Sesión" class="btn btn-primary"/>
              </div>
            </div>
          </div>     
        </form>
      </div>            
    </div>
  </div>            
</div>

</div>
</center>