
    <div class="row">
        <div class="col-lg-4 col-md-8 col-lg-offset-4 col-md-offset-2">
            <div class="col-lg-12 col-md-12 text-center">
                <h2>Login <i class="fa fa-user-friends"></i></h2>        
            </div>
            <div class="col-lg-12 col-md-12">
                <h4 class="text-center inner-padding">Ingrese las credenciales para poder acceder </h4>
                <form method="POST" action="/index/validar">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <div class="form-group">
                                <label><i class="fa fa-user" aria-hidden="true"></i> Correo</label>
                                <input type="text" name="mail"  class="form-control"/>    
                            </div>
                            <div class="form-group">
                                <label><i class="fa fa-lock" aria-hidden="true"></i> Contraseña</label>
                                <input type="password" name="passw" class="form-control"/> 
                                <a href="tokens/index"><h6>Olvide Contraseña</h6></a> 
                            </div>
                            <div class="form-group text-center">
                               <input type="submit" value="Iniciar Sesión" class="btn btn-primary"/>
                           </div>
                       </div>
                   </div>     
               </form>
           </div>            
       </div>
   </div>