<div>
<br><a data-toggle="modal" data-target="#myModal" class="btn btn-info" href="#">AGREGAR NUEVO</a>
</div>

<div class="modal fades" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

	<div class="modal-dialog" style="background-color: white;">
		<div clas="modal-content">

			<form method="POST" action="/panele/requestadduser" enctype="multipart/form-data">
				<div class="modal-header">
					<h4 class="model-title" id="myModalLabel">NUEVO USUARIO:</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<div>
						<input type="hidden" name="rol" value="2">
						<div class=""></div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Fecha: </h4></label>
							<p><input type="text" name="date" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Hora: </h4></label>
							<p><input type="text" name="hour" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Responsable: </h4></label>
							<p><input type="text" name="resp" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Nombre del Cliente: </h4></label>
							<p><input type="text" name="clie" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Telefono: </h4></label>
							<p><input type="text" name="phone" class="form-control" onkeypress="return numeros(event)" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Email: </h4></label>
							<p><input type="text" name="mail" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Direccion: </h4></label>
							<p><input type="password" name="dir" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Descripcion: </h4></label>
							<p><input type="password" name="desc" class="form-control" required></p>
						</div>
					</div>
					<!-- Boton -->
					<!-- Boton -->
				</div>
				<div class ="modal-footer">
					<button type="button" class="btn btn-default" data-dismmiss="modal">CERRAR</button>
					<button type="submit" class="btn btn-primary">GUARDAR </button>
					
				</div>
			</form>
			
		</div>	

	</div>
</div>
