<div class="row">
	<br><a class="btn btn-success" href="/panela/nuevoservicio">AGREGAR</a>
</div>
<br>
<div class="row">
	<table class="table text-left table-hover"> 
		<thead>
			<th>Empresas</th>
			<th>DIRECCION</th>
			<th>CORREO</th>
			<th>TELEFONO</th>
			<th>GERENTE</th>
		</thead>
		<tbody>
			<td>
				<?php foreach ($this->empresas as $emp): ?>
					<?php echo $emp['nombree']; ?> 
					<?php echo $emp['estado']; ?>
					<td><?php echo $emp['direccion']; ?></td>
					<td><?php echo $emp['correo']; ?></td>
					<td><?php echo $emp['telefono']; ?></td>
					<td><?php echo $emp['nombreg']; ?></td>
				</tbody>
			<?php endforeach ?>
		</td>
		<table class="table text-left table-hover"> 
			<thead>
				<th>Vector(es)</th>
			</thead>
			<?php foreach ($this->servicios as $serv): ?>
				<td>
					<?php foreach ($this->vecform as $vefo): ?>
						<?php if ($serv["id"]==$vefo["form"]): ?>
							<?php foreach ($this->vectores as $vect): ?>
								<?php if ($vefo["vector"]==$vect["id"]): ?>
									<?php echo $vect["nombre"].","; ?>
								<?php endif ?>
							<?php endforeach ?>
						<?php endif ?>
					<?php endforeach ?>
				</td>
			</table>
			<table class="table text-left table-hover">
				<thead>
					<th>Descripcion</th>
					<th>Comentarios</th>
				</thead>
				<tbody>
					<td><?php echo $serv['descripcion']; ?></td>
					<td><?php echo $serv['comentarios']; ?></td>
					<td>
					</tbody>
				<?php endforeach ?>
			</table>
		</div>