<div class="row">
	<table class="table text-left table-hover"> 
		<thead>
			<th>Empresas</th>
			<th>Estado</th>
			<th>DIRECCION</th>
			<th>CORREO</th>
			<th>TELEFONO</th>
			<th>GERENTE</th>
		</thead>
		<tbody>
			<?php foreach ($this->empresas as $emp): ?>
				<td><?php echo $emp['nombree']; ?> </td>
				<td><?php echo $emp['estado']; ?></td>
				<td><?php echo $emp['direccion']; ?></td>
				<td><?php echo $emp['correo']; ?></td>
				<td><?php echo $emp['telefono']; ?></td>
				<td><?php echo $emp['nombreg']; ?></td>
			<?php endforeach ?>
		</tbody>
	</table>
</div>

<div class="row">
	<table class="table text-left table-hover"> 
		<thead>
			<th>Vector(es)</th>
		</thead>
		<tbody>
			<?php foreach ($this->servicios as $serv): ?>
				<td>
					<?php foreach ($this->vecform as $vefo): ?>
						<?php if ($serv["id"]==$vefo["form"]): ?>
							<?php foreach ($this->vectores as $vect): ?>
								<?php if ($vefo["vector"]==$vect["id"]): ?>
									<?php echo $vect["nombre"].","; ?>
								<?php endif ?>
							<?php endforeach ?>
						<?php endif ?>
					<?php endforeach ?>
				</td>
			<?php endforeach ?>
		</tbody>
	</table>
</div>

<div class="row">
	<table class="table text-left table-hover">
		<thead>
			<th>Descripcion</th>
			<th>Comentarios</th>
		</thead>
		<tbody>
			<?php foreach ($this->servicios as $serv): ?>
				<td><?php echo $serv['descripcion']; ?></td>
				<td><?php echo $serv['comentarios']; ?></td>
			<?php endforeach ?>
		</tbody>
	</table>
</div>