<div class="row">
	<table class="table text-left table-hover"> 
		<br><a data-toggle="modal" data-target="#myModal" class="btn btn-info" href="#">AGREGAR</a>
		<thead>
			<th>NOMBRE</th>
			<th>DIRECCION</th>
			<th>CORREO</th>
			<th>TELEFONO</th>
			<th>NOMBRE GERENTE</th>
			<th>CREADO</th>
			<th>ESTADO</th>
			<th>EDITAR</th>
			<th>ELIMINAR</th>
		</thead>
		<?php foreach ($this->empresas as $emp): ?>
			<tbody>
				<td><?php echo $emp['nombree']; ?></td>
				<td><?php echo $emp['direccion']; ?></td>
				<td><?php echo $emp['correo']; ?></td>
				<td><?php echo $emp['telefono']; ?></td>
				<td><?php echo $emp['nombreg']; ?></td>
				<td><?php echo $emp['creado']; ?></td>
				<td><?php echo $emp['estado']; ?></td>
				<td><a href="/panela/empresasedit/id/<?php echo $emp['id']; ?>"><i class="fas fa-2x fa-edit"></i></a></td>
				<td><a href="/panela/requestdeleteemp/id/<?php echo $emp['id']; ?>"><i class="fas fa-2x fa-trash-alt" style="color: red;"></i></a></td>
			</tbody>
		<?php endforeach ?>
	</table>
	
</div>
<div class="modal fades" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

	<div class="modal-dialog" style="background-color: white;">
		<div clas="modal-content">

			<form method="POST" action="/panela/requestaddemp" enctype="multipart/form-data">
				<div class="modal-header">
					<h4 class="model-title" id="myModalLabel">NUEVA EMPRESA:</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<div>
						<input type="hidden" name="rol" value="2">
						<div class=""></div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Nombre: </h4></label>
							<p><input type="text" name="name" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4> Direccion:: </h4></label>
							<p><input type="text" name="dir" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Correo: </h4></label>
							<p><input type="text" name="mail" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Telefono: </h4></label>
							<p><input type="text" name="telf" class="form-control" onkeypress="return numeros(event)" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Nombre Gerente: </h4></label>
							<p><input type="text" name="gere" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Estado: </h4></label>
							<p><input type="text" name="estado" class="form-control" required></p>
						</div>
	
					</div>
				</div>
				<div class ="modal-footer">
					<button type="submit" class="btn btn-primary">GUARDAR </button>
					
				</div>
			</form>
			
		</div>	

	</div>
</div>