<div class="row">
	<br><a class="btn btn-info" href="/panela/nuevoservicio">AGREGAR</a>
</div>
<br>

<div class="row">
	<table class="table text-left table-hover"> 
		<thead>
			<th>Descripcion</th>
			<th>Comentarios</th>
		</thead>
		<?php foreach ($this->servicios as $serv): ?>
			<tbody>
				<td><?php echo $serv['descripcion']; ?></td>
				<td><?php echo $serv['comentario']; ?></td>
				<td><a href="/panela/empresasedit/id/<?php echo $serv['id']; ?>"><i class="fas fa-2x fa-edit"></i></a></td>
				<td><a href=""><i class="fas fa-2x fa-trash-alt" style="color: red;"></i></a></td>
			</tbody>
		<?php endforeach ?>
	</table>
</div>