<script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
<form method="POST" action="/panela/requestaddnuevoservicio" enctype="multipart/form-data">

<div>
	<div>
		<select name="emp" class="form-control" required>
			<option value="">
				SELECCIONE EMPRESA
					<?php foreach ($this->empresas as $emp){  ?>
						<option value="<?php echo $emp["id"]; ?>"><?php echo $emp["nombree"]; ?> <?php echo $emp["estado"]; ?>
						</option>
					<?php } ?>
				</select>
			</option>

		</select>
	</div>
	<div>
		<br></br>
		<div class="row">
				<?php foreach ($this->vector as $vec) { ?>
				<div class="col-md-2">
					<input type="checkbox" name="option[]" value="<?php echo $vec["id"]; ?>"><?php echo $vec["nombre"]; ?></input><br>
				</div>
					<?php } ?>
			</div>
			
	</div>
	<br></br>
	<div class="col-md-12">
		<label for="text">Descripción:</label>
		<textarea class="" id="editorDescripcion" rows="100" cols="100"  name="descrip"></textarea>
		<script type="text/javascript">CKEDITOR.replace( 'editorDescripcion',{
			height : 100,
		}); </script>
	</div>
	<br></br>
	<div class="col-md-12">
		<label for="text">Comentarios:</label>
		<textarea class="" id="editorComentario" rows="100" cols="100"  name="coment"></textarea>
		<script type="text/javascript">CKEDITOR.replace( 'editorComentario',{
			height : 100,
		}); </script>
	</div>
<button type="submit" class="btn btn-primary">GUARDAR </button>
</form>

