<div class="row">
	<table class="table text-left table-hover"> 
		<thead>
			<th>NOMBRE</th>
			<th>CORREO</th>
			<th>APELLIDO P</th>
			<th>APELLIDO M</th>
			<th>DIRECCION</th>
			<th>TELEFONO</th>
			<th>ROL</th>
			<th>CREADO</th>
		</thead>
		<?php foreach ($this->usuarios as $usr): ?>
			<tbody>
				<td><?php echo $usr['nombre']; ?></td>
				<td><?php echo $usr['correo']; ?></td>
				<td><?php echo $usr['apellidop']; ?></td>
				<td><?php echo $usr['apellidom']; ?></td>
				<td><?php echo $usr['direccion']; ?></td>
				<td><?php echo $usr['telefono']; ?></td>
				<td><?php echo $usr['rol']; ?></td>
				<td><?php echo $usr['creado']; ?></td>
			</tbody>
		<?php endforeach ?>
	</table>
	<br><a data-toggle="modal" data-target="#myModal" class="btn btn-info" href="#">AGREGAR NUEVO</a>
</div>

<div class="modal fades" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

	<div class="modal-dialog" style="background-color: white;">
		<div clas="modal-content">

			<form method="POST" action="/panela/requestadduser" enctype="multipart/form-data">
				<div class="modal-header">
					<h4 class="model-title" id="myModalLabel">NUEVO USUARIO:</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<div>
						<input type="hidden" name="rol" value="2">
						<div class=""></div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Nombre(s): </h4></label>
							<p><input type="text" name="name" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Apellido paterno: </h4></label>
							<p><input type="text" name="apa" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Apellido materno: </h4></label>
							<p><input type="text" name="ama" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Dirección: </h4></label>
							<p><input type="text" name="dir" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Telefono: </h4></label>
							<p><input type="text" name="phone" class="form-control" onkeypress="return numeros(event)" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Correo electronico: </h4></label>
							<p><input type="text" name="mail" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Contraseña: </h4></label>
							<p><input type="password" name="pword" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Confirme contraseña: </h4></label>
							<p><input type="password" name="pwordc" class="form-control" required></p>
						</div>
					</div>
					<!-- Boton -->
					<!-- Boton -->
				</div>
				<div class ="modal-footer">
					<button type="button" class="btn btn-default" data-dismmiss="modal">CERRAR</button>
					<button type="submit" class="btn btn-primary">GUARDAR </button>
					
				</div>
			</form>
			
		</div>	

	</div>
</div>

<script type="text/javascript">
	function numera(e){
		key = e.keycode ||e.wich;
		tecla = String.fromCharCode(key).toLowerCase();
		letras = " 0123456789";
		especiales = [8,37,39,46];

		tecla-especial = false
		for(var i in especiales){
			if(key == especiales[i]){
				tecla_especial = true;
				break;
			}
		}
		if(letras.indexOF(tecla)== i && !tecla_especial)
			return false;
	}

</script>