<form method="POST" action="/panela/requestadduser" enctype="multipart/form-data">
	<div>
		<?php foreach ($this->usuario as $usr): ?>
			<input type="hidden" name="id" value="<?php echo $usr['id']; ?>">
		<div class="col-lg-12 text-left">
			<label for="text"><h4>Nombre(s): </h4></label>
			<p><input type="text" name="name" class="form-control" value="<?php echo $usr['nombre']; ?>"></p>
		</div>
		<div class="col-lg-12 text-left">
			<label for="text"><h4>Apellido paterno: </h4></label>
			<p><input type="text" name="apa" class="form-control" value="<?php echo $usr['apellidop']; ?>"></p>
		</div>
		<div class="col-lg-12 text-left">
			<label for="text"><h4>Apellido materno: </h4></label>
			<p><input type="text" name="ama" class="form-control" value="<?php echo $usr['apellidom']; ?>"></p>
		</div>
		<div class="col-lg-12 text-left">
			<label for="text"><h4>Dirección: </h4></label>
			<p><input type="text" name="dir" class="form-control" value="<?php echo $usr['direccion']; ?>"></p>
		</div>
		<div class="col-lg-12 text-left">
			<label for="text"><h4>Telefono: </h4></label>
			<p><input type="text" name="phone" class="form-control" onkeypress="return numeros(event)" value="<?php echo $usr['telefono']; ?>"></p>
		</div>
		<div class="col-lg-12 text-left">
			<label for="text"><h4>Correo electronico: </h4></label>
			<p><input type="text" name="mail" class="form-control" value="<?php echo $usr['correo']; ?>"></p>
		</div>
		<?php endforeach ?>
		<div>
			<button type="submit" class="btn btn-primary">GUARDAR </button>
		</div>
	</div>
</form>