<div class="row">
	<table class="table text-left table-hover"> 
		<thead>
			<th>Nombre</th>
			<th>Correo</th>
			<th>Apellido Paterno</th>
			<th>Apellido Materno</th>
			<th>Direccion</th>
			<th>Telefono</th>
			<th>Cargo</th>
			<th>Creado</th>
			<th>Editar</th>
			<TH>Eliminar</TH>
		</thead>
		<?php foreach ($this->usuarios as $usr): ?>
			<tbody>
				<td><?php echo $usr['nombre']; ?></td>
				<td><?php echo $usr['correo']; ?></td>
				<td><?php echo $usr['apellidop']; ?></td>
				<td><?php echo $usr['apellidom']; ?></td>
				<td><?php echo $usr['direccion']; ?></td>
				<td><?php echo $usr['telefono']; ?></td>
				<?php if ($usr['rol']==1): ?>
					<td><?php echo "Administrador"; ?></td>
				<?php else: ?>
					<td><?php echo "Empleado"; ?></td>
				<?php endif ?>
				<td><?php echo $usr['creado']; ?></td>
				<td><a href="/panela/usuariosedit/id/<?php echo $usr['id']; ?>"><i class="fas fa-2x fa-edit"></i></a></td>
				<td><a href="/panela/requestdeleteusr/id/<?php echo $usr['id']; ?>"><i class="fas fa-2x fa-trash-alt" style="color: red;"></i></a></td>
			</tbody>
		<?php endforeach ?>
	</table>

	<br><a data-toggle="modal" data-target="#myModal" class="btn btn-info" href="#">AGREGAR NUEVO</a>
</div>

<div class="modal fades" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" style="background-color: white;">
		<div clas="modal-content">

			<form method="POST" action="/panela/requestadduser" enctype="multipart/form-data">
				<div class="modal-header">
					<h4 class="model-title" id="myModalLabel">NUEVO USUARIO:</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<div>
						<input type="hidden" name="rol" value="2">
						<div class=""></div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Nombre(s): </h4></label>
							<p><input type="text" name="name" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Apellido paterno: </h4></label>
							<p><input type="text" name="apa" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Apellido materno: </h4></label>
							<p><input type="text" name="ama" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Dirección: </h4></label>
							<p><input type="text" name="dir" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Telefono: </h4></label>
							<p><input type="text" name="phone" class="form-control" onkeypress="return numeros(event)" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Correo electronico: </h4></label>
							<p><input type="text" name="mail" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Contraseña: </h4></label>
							<p><input type="password" name="pword" class="form-control" required></p>
						</div>
						<div class="col-lg-12 text-left">
							<label for="text"><h4>Confirme contraseña: </h4></label>
							<p><input type="password" name="pwordc" class="form-control" required></p>
						</div>
					</div>
				</div>
				<div class ="modal-footer">
					<button type="submit" class="btn btn-primary">GUARDAR </button>
					
				</div>
			</form>
			
		</div>	

	</div>
</div>

<script type="text/javascript">
	function numeros(e){
		key = e.keyCode || e.which;
		tecla = String.fromCharCode(key).toLowerCase();
		letras = " 0123456789";
		especiales = [8,37,39,46];

		tecla_especial = false
		for(var i in especiales){
			if(key == especiales[i]){
				tecla_especial = true;
				break;
			} 
		}

		if(letras.indexOf(tecla)==-1 && !tecla_especial)
			return false;
	}
</script>

<script>
	var pword, pwordc;

	pword = document.getElementById('pword');
	pwordc = document.getElementById('pwordc');

	pword.onchange = pwordc.onkeyup = passwordMatch;

	function passwordMatch() {
	    if(pword.value !== pwordc.value)
	        pwordc.setCustomValidity('Las contraseñas no coinciden.');
	    else
	        pwordc.setCustomValidity('');
	}  
</script>