<?php $session = new Zend_Session_Namespace("current_session"); ?>
<!-- la linea anterior controla las sesiones -->
<!doctype html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Titulo del proyecto</title>

	<!-- Not modify -->
	<link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css">	
	<link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
	<link rel="stylesheet" href="/css/swiper.css">

	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/tether.min.js"></script>	
	<script type="text/javascript" src="/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/ohsnap.js"></script>
		<script type="text/javascript" src="/js/moment.js"></script>
	<script type="text/javascript" src="/js/bootstrap-datetimepicker.js"></script>
	<!-- Not modify -->
</head>
<body>
	
</body>	
</html>