<?php $session = new Zend_Session_Namespace("current_session");
 ?>
<!DOCTYPE html>
<html>
<head>
	<title>S I C O P L A S Panel: Administrador</title>
	<!-- Not modify -->
	<link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css">	
	<link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
	<link rel="stylesheet" href="/css/swiper.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates:400,500,700,700i,800,900,900i" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,800,800i,900|Simonetta:400,400i,900,900i" rel="stylesheet">

	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/tether.min.js"></script>	
	<script type="text/javascript" src="/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/ohsnap.js"></script>
	<script type="text/javascript" src="/js/moment.js"></script>
	<script type="text/javascript" src="/js/bootstrap-datetimepicker.js"></script>
	<!-- Not modify -->

	<style type="text/css">
	.title-nav{
		font-family: 'Montserrat Alternates', sans-serif;
		font-size: 18px;		
		}
	h1,h2,h3,h4,h5,h6{font-family: 'Montserrat Alternates', sans-serif;}
	.links{font-family: 'Montserrat', sans-serif;}
	</style>

</head>
<body background="/img/img_back/logback.jpg">
	<div class="container">
		<nav class="navbar navbar-toggleable-lg navbar-expand-lg navbar-light bg-light">
			<img src="/img/sico.png" width="40" height="40"><label class="navbar-brand title-nav" > S I C O P L A S </label>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav title-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="/panela/index">Gestion de Servicios</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/panela/usuarios">Gestion de Usuarios</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/panela/empresas">Gestion de Empresas</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/panela/vector">Gestion de Vectores</a>
					</li>
					
				</ul>
				<ul class="navbar-nav my-2 my-md-0 title-nav">
					<li class="nav-item">
						<a class="nav-link" href="/index/logout">Cerrar Sesion</a>
					</li>
				</ul>
			</div>
		</nav>
	</div>
	<!-- Contenido -->
	<div class="container"><br>
		<?php echo $this->layout()->content; ?><br>
	</div>
</body>
</html>