<?php foreach ($this->recomendation as $key => $value) { 
	if ($value['nombre']=="Clasico") {
		$reco=$value['id'];
		$cla=$value['imagen'];
	}
	if ($value['nombre']=="Ella") {
		$reco1=$value['id'];
		$ela=$value['imagen'];
	}
	if ($value['nombre']=="El") {
		$reco2=$value['id'];
		$el=$value['imagen'];
	}
} ?>

<h1>TEMPORADA DE FLORES</h1>
<div class="row">
	
	<div class="col-lg-4 text-center">
		<a href="/home/productosrecomendacion/id/<?php echo $reco; ?>"><img src="/<?php echo $cla; ?>" width="360" height="520">
		<label>Clasico</label></a>
	</div>
	<div class="col-lg-4 text-center">
		<a href="/home/productosrecomendacion/id/<?php echo $reco1; ?>"><img src="/<?php echo $ela; ?>" width="360" height="520">
			<label>Ella</label></a>
	</div>
	<div class="col-lg-4 text-center">
		<a href="/home/productosrecomendacion/id/<?php echo $reco2; ?>"><img src="/<?php echo $el; ?>" width="360" height="520">
			<label>Él</label></a>
	</div>
	
</div>
